# Harmony Jekyll theme general configurations 

# Base URL
# baseurl: /blog

# Site live URL
url: http://smasue.github.io

# Localhost
#url: http://127.0.0.1:4000
name: Samuel Masue
description: Yet another tech blog! Let's talk about Alfresco, Java, Linux, ...

# Harmony theme configuration. Please change accordingly.
harmony:
  meta_description: I am Samuel Masue. This blog will cover topics about Alfresco.
  basetheme: theme-base-01 # pre defined themes are darken, blue-water, redish.
  author: # Author details
    name: Samuel Masue
    email: samuel.masue@gmail.com
    url: http://smasue.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-62556774-1

  # Profile links, leave blank to ignore
  social: 
    github: smasue
    twitter: SamMcCandless
    linkedin: smasue
    gplus: +samuelmasué
    rss: feed.xml
    
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
    
gems: [git]
