# Harmony Jekyll theme general configurations 

# Base URL
# baseurl: /blog

# Site live URL
url: http://alireza6677.github.io

# Localhost
#url: http://127.0.0.1:4000
name: فعلا بدون نام :)
description: کمی لینوکس ،‌پایتون و جاوا در کنار هم
dir: rtl
# Harmony theme configuration. Please change accordingly.
harmony:
  meta_description: وبلاگی در مورد همه چیز
  basetheme: theme-base-01 # pre defined themes are darken, blue-water, redish.
  author: # Author details
    name: Alireza S.N
    email: alireza6677@gmail.com
    url: http://alireza6677.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key:

  # Profile links, leave blank to ignore
  social: 
    github: alireza6677
    twitter: alireza6677
    rss: feed.xml
    
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
    
gems: [git,jekyll-gist]
